ARG PYTHON_VERSION=3.9.8

FROM python:${PYTHON_VERSION} AS base

WORKDIR /app

COPY auth-web.json /app/auth-web.json
COPY youtube-music.py /app/youtube-music.py


RUN pip3 install requests datetime google-api-python-client schedule google-auth google-auth-oauthlib 

CMD ["python3", "/app/youtube-music.py"]
